name: PazaBot NASA Daily Sender

on:
  schedule:
    # Roda todo dia às 8:00 UTC (07:00 Brasil)
    - cron: '0 10 * * *' 
  
  # Permite clicar no botão "Run" para testar na hora
  workflow_dispatch:

jobs:
  run-pazabot:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código (Checkout)
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' 

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt

      - name: Rodar o PazaBot
        env:
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python main.py
